FROM node:12.7.0-stretch as builder

COPY . /app

WORKDIR /app

RUN npm install

RUN npm run build

FROM node:12.7.0-alpine

RUN npm install -g serve

RUN apk --no-cache add bash

COPY --from=builder /app/build/ ./build

CMD ["serve", "-s", "build"]
