version: '3'
services:
  taurus-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - taurus-network

networks:
  taurus-network:
    external: true
